### ISSUE TITLE
Export Layers Jpeg error.

### ISSUE THREAD

**Issue by LiamTrioTech** [photopea/photopea#2409]
Export layers as JPG has error.

Only when Remove parts outside the canvas & Trim transparent parts are checked.

```
Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number.
    at Function.hJ.QA (https://www.photopea.com/code/pp.js:192:110)
    at Function.hJ.f7 (https://www.photopea.com/code/pp.js:188:120)
    at Object.hJ.YS.Hb (https://www.photopea.com/code/pp.js:244:56)
    at Function.hJ.ov (https://www.photopea.com/code/pp.js:203:55)
    at Function.l.XW.yl (https://www.photopea.com/code/pp.js:4721:54)
    at fP.zd (https://www.photopea.com/code/pp.js:8832:73)
    at ek.bW.A (https://www.photopea.com/code/pp.js:9:11)
    at ek.a2.A (https://www.photopea.com/code/pp.js:7526:43)
    at ek.C0 (https://www.photopea.com/code/pp.js:7684:34)
2pp.js:9808 -1
pp.js:10605 systemCopy
```

**Comment by photopea** [comment]
Hi, I think I fixed the problem. Could you try it again?

If it still does not work, could you send your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
"installing" Photopea just adds an icon to your homescreen. But it is still a website, so you can simply close it and open it again to "update" a website.

**Comment by photopea** [comment]
yes that is correct. Once you open Photopea, you can disconnect from the internet and work offline.
