### ISSUE TITLE
Take a picture without camera

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#345]
File - Take a picture
It correctrly announces "Access to the camera was denied." (I have no camera...)
But window is still opened showing "Resolution:0 x 0px"
And after I click button "Current project" or "New project" it shows this error in console:
pp.js:4756 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Yj.GB (https://www.photopea.com/code/pp.js:4756:84)
    at Yj.fA (https://www.photopea.com/code/pp.js:4758:110)
    at YQ.RK.D (https://www.photopea.com/code/pp.js:6:49)
    at YQ.Yx.D (https://www.photopea.com/code/pp.js:4117:43)
    at YQ.an (https://www.photopea.com/code/pp.js:4196:95)

**Comment by photopea** [comment]
It was fixed. Thank you!
