### ISSUE TITLE
Typing tool is not working

### ISSUE THREAD

**Issue by dayramaelbranz** [photopea/photopea#4264]
Not able to type after clicking the Typing Tool.

**Comment by Preta-Crowz** [comment]
Same, here's log from mine
```
pp.js:8923 Uncaught TypeError: Cannot read properties of undefined (reading 'StyleSheet')
    at Function.dF.mU (pp.js:8923:36)
    at g.Ek.co (pp.js:5888:55)
    at g.Ek.VW (pp.js:5933:106)
    at iP.atb (pp.js:13376:141)
    at iP.hp.m (pp.js:9317:49)
    at iP.aF.m (pp.js:9322:43)
    at h3.aF.m (pp.js:9322:100)
    at gZ.aF.m (pp.js:9322:100)
    at aJ.aF.m (pp.js:9322:100)
    at aJ.h_ (pp.js:9341:19)
pp.js:8888 Uncaught TypeError: Cannot read properties of null (reading '_R')
    at Function.dF.yb (pp.js:8888:107)
    at g.Ek.Zp (pp.js:5991:27)
    at g.Ek.k1 (pp.js:5920:110)
    at iP.atb (pp.js:13376:63)
    at iP.hp.m (pp.js:9317:49)
    at iP.aF.m (pp.js:9322:43)
    at h3.aF.m (pp.js:9322:100)
    at gZ.aF.m (pp.js:9322:100)
    at aJ.aF.m (pp.js:9322:100)
    at aJ.yq (pp.js:9338:95)
```

**Comment by Preta-Crowz** [comment]
It looks like it's same as #4263

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
