### ISSUE TITLE
Script error causes plugin not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4678]
My "Similar Letter" plugin is not working due to script error.
As part of my more complicated script sent to photopea I am using this script to create Group (LayerSet) and Layer inside this new group. I am pretty sure this was working before:
```
        // Create temporary new layer
        app.activeDocument.activeLayer = app.activeDocument.layers[0];
        var group = app.activeDocument.layerSets.add();
        var layer = group.artLayers.add();
```

Now it just show this error in console:

```
pp.js:9409 Uncaught TypeError: Cannot read properties of undefined (reading 'root')
    at cd.pt.TM (pp.js:9409:48)
    at cd.eval (pp.js:9360:23)
    at cd.CM (pp.js:9395:96)
    at cd.eval (pp.js:9368:88)
    at cd.CM (pp.js:9395:96)
    at cd.eval (pp.js:9359:102)
    at cd.eval (pp.js:9359:31)
    at cd.eval (pp.js:9357:38)
    at cd.DC (pp.js:9354:70)
    at eU.yd (pp.js:13707:117)
```

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
