### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by Hanprogramer** [photopea/photopea#5241]
```
Uncaught TypeError: UPNG.encode is not a function
    at eZ.Pr.z8 (pp.js:355:60)
    at eZ.nk (pp.js:300:59)
    at P.Tb.bL (pp.js:6503:16)
    at jr.asK (pp.js:10837:113)
    at jr.$ (pp.js:10835:128)
    at dn.ahk (pp.js:12544:41)
    at new dn (pp.js:12513:46)
    at new c0 (pp.js:12803:40)
    at iq.aa (pp.js:14993:340)
    at iq.aBN (pp.js:14999:27)
```

**Comment by Luckstyle** [comment]
I'm having the same issue

**Comment by acupofsunshinetea** [comment]
i'm able to open jpgs and pngs by dragging them into the window but can't export or use image size/canvas size.

**Comment by photopea** [comment]
Just clear your cache, or wait an hour (you can use Photopea in the Incognito mode for the next hour).
