### ISSUE TITLE
saveToOE("jpg") fails (when called without a quality parameter) after a gradient is drawn

### ISSUE THREAD

**Issue by zalo** [photopea/photopea#5330]
Using "webp" or adding a quality parameter (ala `"jpg:0.6"`) lets images containing gradients work again.

When it fails, this is its stack trace:
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at h0.ue.q_ (pp.js:389:101)
    at h0.DR (pp.js:314:115)
    at cd.ct (pp.js:14434:168)
    at cd.abi (pp.js:14435:64)
    at e9.NG (pp.js:14698:90)
    at jc.c (pp.js:10260:49)
    at a_.c (pp.js:10265:77)
    at a9.lz.$V (pp.js:10158:84)
    at a9.eval (pp.js:9998:57)
    at a9.eval (pp.js:9990:165)
```

**Comment by photopea** [comment]
Could you tell me what should I do to see the error myself?

What is a gradient? Do you mean making a raster gradient with a Gradient tool?

Also try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by zalo** [comment]
Sure, here's minimal reproduction steps:
1. Open Photopea Fresh
2. Open the Script Console and paste in `app.open("https://i.imgur.com/R6xOBld.jpg", null, false);`
3. Use the raster gradient tool
4. Paste `activeDocument.saveToOE("jpg");` into the script console

![PhotopeaError](https://user-images.githubusercontent.com/174475/216304267-ce4768b9-b6f5-4b10-ba5e-f1b2ce5f0f0e.gif)

**Comment by photopea** [comment]
It was not related to saveToOE(), it happened even with File - Export As - JPG.

**Comment by zalo** [comment]
Thank you!  Your software is excellent (and I make sure to tell all my friends whenever I have the opportunity!)

Have a wonderful day!
