### ISSUE TITLE
Filter Stroke in "Edit" is not working

### ISSUE THREAD

**Issue by softy-oniguru** [photopea/photopea#5687]
In developer tools sends error:

pp.js:2757 Uncaught TypeError: Assignment to constant variable.
    at y.style.Ad (pp.js:2757:15)
    at y.style.stroke (pp.js:2747:134)
    at c.kl.ak1 (pp.js:6533:49)
    at c.Oa.BZ (pp.js:6313:113)
    at bU.BZ (pp.js:15025:3)
    at c7.T (pp.js:10535:49)
    at g8.T (pp.js:10540:77)
    at g8.T (pp.js:10540:134)
    at g8.T (pp.js:10540:134)
    at aw.gZ (pp.js:13201:19)

**Comment by Pt-home** [comment]
Can you show your code if you don't mind? Or at least an action descriptor to a Stroke?

**Comment by photopea** [comment]
Could you reload Photopea in 20 minutes and try it again? It will be fixed.
