### ISSUE TITLE
`doc.selection.select` raises exceptions

### ISSUE THREAD

**Issue by huchenlei** [photopea/photopea#5902]
Reproduction code:

```javascript
var doc = app.activeDocument;
var bounds = [[0, 0], [100, 0], [100, 100], [0, 100]];
doc.selection.select(bounds, SelectionType.REPLACE, 0, false);
```

Throws following exception in the [playground](https://www.photopea.com/api/playground):
```
pp.js:10319 Uncaught TypeError: Cannot read properties of null (reading 'V')
    at fv.eval (pp.js:10319:89)
    at fv.h9 (pp.js:10359:16)
    at fv.eval (pp.js:10325:72)
    at fv.eval (pp.js:10322:165)
    at fv.eval (pp.js:10315:99)
    at fv.sc (pp.js:10312:84)
    at ij.Ns (pp.js:15224:118)
    at fq.T (pp.js:10606:49)
    at aD.T (pp.js:10611:77)
    at ij.<anonymous> (pp.js:15061:34)
```

Am I doing anything wrong here? I am referencing https://stackoverflow.com/questions/43682323/selecting-a-certain-area-of-a-layer-in-photoshop-script-js.

Changing numbers to `UnitValue` does not help. Following code gives the same error stack.
```
var doc = app.activeDocument;
var bounds = [0, 0, 100, 100];
doc.selection.select([
    [new UnitValue(bounds[0], "px"), new UnitValue(bounds[1], "px")], // Top-left
    [new UnitValue(bounds[2], "px"), new UnitValue(bounds[1], "px")], // Top-right
    [new UnitValue(bounds[2], "px"), new UnitValue(bounds[3], "px")], // Bottom-right
    [new UnitValue(bounds[0], "px"), new UnitValue(bounds[3], "px")]  // Bottom-left
], SelectionType.REPLACE, 0, false);
```

**Comment by Pt-home** [comment]
Its work:
var doc = app.activeDocument;
var bounds = [[0, 0], [100, 0], [100, 100], [0, 100]];
doc.selection.select(bounds, REPLACE, 0, false);

**Comment by huchenlei** [comment]
Ok, I think the problem is `SelectionType.REPLACE`. In photopea `REPLACE` lives in global scope. Thanks for explaining!

**Comment by photopea** [comment]
It is fixd now. Your original script should work now.
