### ISSUE TITLE
Magic Replace not working

### ISSUE THREAD

**Issue by MellowFishy** [photopea/photopea#6346]
Your Operating System: Windows 11
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Buy premium
3. Use magic replace

pp.js:6697 Uncaught ReferenceError: AI is not defined
    at B.kK.Uu (pp.js:6697:53)
    at fB.Uu (pp.js:15902:3)
    at jL.D (pp.js:11206:49)
    at dS.D (pp.js:11211:77)
    at j7.aoh (pp.js:9101:43)
    at fB.abG (pp.js:15902:101)
    at jL.D (pp.js:11206:49)
    at dS.D (pp.js:11211:77)
    at dS.D (pp.js:11211:134)
    at dS.D (pp.js:11211:134)
﻿

**Comment by camoody1** [comment]
@photopea I just checked with Dezgo, and they say their side is working correctly as far as they can see.

**Comment by photopea** [comment]
Sorry, it is fixed now.
