### ISSUE TITLE
Image trim crashes Photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#690]
Open pea.psd
Go to "top bar" layer
Select Image->Trim (in main menu)
-> Crash
Uncaught DOMException: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Object.T.G_.Ga (https://www.photopea.com/code/pp.js:991:70)
    at YU._P (https://www.photopea.com/code/pp.js:3946:72)
    at YU._P (https://www.photopea.com/code/pp.js:3949:106)
    at YY.QN (https://www.photopea.com/code/pp.js:4069:63)
    at Am.update (https://www.photopea.com/code/pp.js:6717:53)
    at Am.mL (https://www.photopea.com/code/pp.js:6715:15)

**Comment by photopea** [comment]
It was fixed. Thanks!
