### ISSUE TITLE
Nothing appears on the photopea website

### ISSUE THREAD

**Issue by Minespro** [photopea/photopea#7071]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. A blank white screen will appear
3. Going into elements in inspect mode shows that nothing exists on the website

**Comment by photopea** [comment]
Do you see any errors in a web console?

**Comment by Minespro** [comment]
These are the two errors that appear
 
Uncaught SyntaxError: Invalid or unexpected token
 
Uncaught ReferenceError: BINDB is not defined
    at Object.get (pp1724065681.js:337:157)
    at pp1724065681.js:478:93
    at pp1724065681.js:480:59
    at pp1724065681.js:16786:163

**Comment by Ksandr707-yt** [comment]
Same problem

**Comment by Minespro** [comment]
Update to the first error:

Instead of Uncaught SyntaxError: Invalid or unexpected token
it now shows Uncaught SyntaxError: Invalid or unexpected token (at DBS1722173946.js:12941:3)

**Comment by photopea** [comment]
I think some of your browser extensions might be rewriting our Javascript. Did you try to run Photopea without any browser extensions?

**Comment by Ksandr707-yt** [comment]
I've tried. No result. In Edge browser, for example, site works.

**Comment by Minespro** [comment]
Same here the only extension i have is Adobe Acrobat and running without it does not do anything

**Comment by photopea** [comment]
Could anyone show me a screenshot with Photopea.com and the drop-down menu of your extensions?  https://i.imgur.com/VDzo5rg.png

**Comment by Ksandr707-yt** [comment]
![image](https://github.com/user-attachments/assets/0abd9a99-723c-4868-a268-4c8142199f66)
![image](https://github.com/user-attachments/assets/e7e586ea-63da-4b34-94c9-e8e681c47f84)
Only like this because when there is no extensions icon disappears

**Comment by photopea** [comment]
Are both of you located in Russia? Or where are you located?

**Comment by photopea** [comment]
Could you open this file https://vecpea.com/code/dbs/DBS1722173946.js , rename it to TXT and share it here with me? Maybe you see a different code than I do - it was modified by someone.

**Comment by Ksandr707-yt** [comment]
> Are both of you located in Russia? Or where are you located?

I'm from Russia

**Comment by Minespro** [comment]
> Could anyone show me a screenshot with Photopea.com and the drop-down menu of your extensions? https://i.imgur.com/VDzo5rg.png

![image](https://github.com/user-attachments/assets/c24ec95d-7d99-4a0b-8a59-414b44875408)

**Comment by photopea** [comment]
You can probably see this error in a web console:  https://imgur.com/a/GJ5V65L

When you see the first error in a file DBS..., can you click it and see the part of the code with the error? Could you show me a screenshot of that?

**Comment by Minespro** [comment]
This is the error. from what i see it looks like something to do with the LUT database i guess?
![image](https://github.com/user-attachments/assets/92f9e54f-4bb0-4ba8-9fcf-79b0d38ba294)

**Comment by Ksandr707-yt** [comment]
Same here

**Comment by photopea** [comment]
If you open the file [DBS1722173946.txt](https://github.com/user-attachments/files/16676888/DBS1722173946.txt) in a Notepad, you can see, that after a line 12941 there are many other lines below it. In your case, the file is cut away.

Are you saying that it happens only in Chrome and not in Edge or other browsers? Do you use a VPN?

**Comment by Ksandr707-yt** [comment]
> If you open the file [DBS1722173946.txt](https://github.com/user-attachments/files/16676888/DBS1722173946.txt) in a Notepad, you can see, that after a line 12941 there are many other lines below it. In your case, the file is cut away.
> 
> Are you saying that it happens only in Chrome and not in Edge or other browsers? Do you use a VPN?

I don't use VPN. I tested only edge browser and there photopea works normally.

**Comment by Ksandr707-yt** [comment]
![image](https://github.com/user-attachments/assets/fa544ffa-9c3b-4f85-90c2-63a0543ff9c0)

**Comment by photopea** [comment]
Could you try Photopea in the Incognito mode?

**Comment by Ksandr707-yt** [comment]
![image](https://github.com/user-attachments/assets/886e4c28-d436-4a17-85df-91f6ce5845aa)

**Comment by Minespro** [comment]
it didn't work earlier but now it works in incognito mode

**Comment by MesaBlack** [comment]
![image](https://github.com/user-attachments/assets/184e4822-dba7-4465-9826-e5dcb2f71712)
chrome os, too

**Comment by photopea** [comment]
I prepared a version of Photopea without a CDN:

https://www.photopea.com/index_nocdn.html

Could you load both Photopea.com and the link above, at the same time, on the same computer in the same browser, next to each other. If one loads and another not, could you tell me?

**Comment by Ksandr707-yt** [comment]
![image](https://github.com/user-attachments/assets/3b375cf6-5e9f-4ed4-9fd3-9ed9fd95d29b)

**Comment by Minespro** [comment]
![image](https://github.com/user-attachments/assets/3d44c47a-e768-4784-b2b8-4a8c5c8d5786)

**Comment by photopea** [comment]
I replaced the DBS...js in the main version with a noCDN version, does Photopea.com work for you now?

**Comment by Ksandr707-yt** [comment]
Yes, thank you so much!

**Comment by Minespro** [comment]
yes thanks i needed to use this for so long

**Comment by MesaBlack** [comment]
What about me?
![image](https://github.com/user-attachments/assets/a9c696ab-3227-474f-bb79-5d474babcfdd)

**Comment by MesaBlack** [comment]
> I replaced the DBS...js in the main version with a noCDN version, does Photopea.com work for you now?

Are you gonna apply it to the installed version, too?

**Comment by photopea** [comment]
I have switched back to a CDN version. Could you check if it still works now for you?

**Comment by Minespro** [comment]
> I have switched back to a CDN version. Could you check if it still works now for you?

Sorry for not replying for so long but yes it still works
