### ISSUE TITLE
Crop tool - Trim problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#794]
Open pea.psd
Go to "top bar" layer
Select "Crop Tool"
Click "Trim" button in toolbar
Click confirm
->
pp.js:1027 Uncaught DOMException: Failed to execute 'createImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Object.J.af.ad (https://www.photopea.com/code/pp.js:1027:70)
    at Qn.aX (https://www.photopea.com/code/pp.js:4258:72)
    at Qn.aX (https://www.photopea.com/code/pp.js:4261:106)
    at Qr.dk (https://www.photopea.com/code/pp.js:4385:63)
    at JF.update (https://www.photopea.com/code/pp.js:7184:53)
    at JF.Zm (https://www.photopea.com/code/pp.js:7182:15)

**Comment by photopea** [comment]
It was fixed. Thanks!
